# Generated by Django 2.2.13 on 2020-10-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
